<?php
session_start();
include "config.php";

// 1. Completely clear the previous screening session to prevent "continuing"
unset($_SESSION['active_screening_id']);

if (isset($_SESSION['user_id'])) {
    $donor_id = $_SESSION['user_id'];

    // 2. The INSERT (This is what triggers a brand new ID)
    // Use NULL for the 'id' column so AUTO_INCREMENT can take over
    $sql = "INSERT INTO screenings (id, donor_id, status, created_at) VALUES (NULL, ?, 'pending', NOW())";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $donor_id);
    
    if ($stmt->execute()) {
        // 3. This catches the NEW ID generated by the database
        $new_id = $conn->insert_id;
        $_SESSION['active_screening_id'] = $new_id;

        // 4. Increment the User's Total Donation Count
        $update_user = "UPDATE users SET total_donations = total_donations + 1 WHERE id = ?";
        $stmt_user = $conn->prepare($update_user);
        $stmt_user->bind_param("i", $donor_id);
        $stmt_user->execute();

        // 5. Success! Redirect to the first form
        header("Location: donor-health-form.php");
        exit();
    } else {
        // This will tell you EXACTLY why the database rejected the new entry
        die("Database Error: " . $stmt->error);
    }
} else {
    die("Error: No user session found. Please log in again.");
}
?>